### ISSUE TITLE
Review, comment and edit: oracles.asciidoc

### ISSUE THREAD

**Issue by aantonop** [ethereumbook/ethereumbook#444] opened 2018-04-09 15:50 UTC
The Oracles section is now in main, ready to be merged into a chapter. It needs review, comments, edits

**Comment by chanan-sack** [comment] 2018-04-09 21:11
it seems good, i could add a section on a way to decentralize oracles using stake-based votes on specific data with different incentive-mechanisms, which of course does not solve the issue, but does broaden the readers understanding of it, should i?

**Comment by smartcontracts** [comment] 2018-04-13 23:00
Grammatical & structural revisions below. Will make another comment with content revisions later.

> While this characteristic is key to Ethereum’s security assurances, the constraints of executing smart contracts within this deterministically walled garden impose strict limitations on their functionality since the retrieval and processing of real-world data from off-chain are prevented.

This is a bit of a run-on sentence.

> Extending the scope of smart contracts to enforce contractual relationship based on real-world events and data broadens their scope dramatically.

"Scope" twice feels off.

> Examples of data that might be provided by oracles include:

I'm not sure the large list of examples of data that can be provided is particularly necessary, but that's up for debate. A few example are very useful.

> In this section, we will examine the primary functions of oracles, subscription patterns, data authentication considerations, the notion of computation oracles, decentralized oracles, before looking at some client implementations in Solidity.

The parallelism here seems off. Maybe something like: "In this section, we will examine the primary functions of oracles, oracle subscription patterns, computation oracles, decentralized oracles, and oracle client implementations in Solidity."? 

> The oracle may also require payment for processing the request, gas payment for the callback, and data permissions or rights obligations might have to be met.

More parallelism. "The oracle may also require payment for processing the request, gas payment for the callback, and permissions/rights to access the requested data."

> Depending on the scheduling parameters, the oracle may broadcast further transactions updating the data at regular intervals, for example, end of day pricing information.

Use of "for example" is erroneous here (the sentence would be off if it were removed). "... regular intervals, e.g. end of day pricing information." probably makes more sense.

> Data can be requested from and returned directly by an externally-controlled account, removing the need for an oracle smart contract, or the request and response can be made to and from an Internet of Things enabled hardware sensor.

Should probably be broken into two sentences. "Data can be requested from and returned directly by an externally-controlled account, removing the need for an oracle smart contract. Similarly, the request and response could be made to and from an Internet of Things enabled hardware sensor."

> - Retrieval of data from an off-chain source
> - Broadcast of transaction to network

Parallelism again. "Retrieving data from an off-chain source", "Broadcasting transactions to the network".

> Given that interest rates change infrequently, a publish-subscribe pattern may be more appropriate here, especially when taking into consideration Ethereum’s limited bandwidth.

Maybe an em-dash instead of a comma before "especially" here? Not sure. Also, we should generally be making sure that em-dashes are used instead of hyphens when intended, e.g. "... publishers - here, oracles - do not ..."

> Subscribers are able to express an interest in one or more classes, retrieving only those messages which are of interest.

"Subscribers are able to express an interest in one or more classes and retrieve only those messages which are of interest."

> A subscribing smart contract could request the full content of the channel if it required the timeseries for, e.g. a moving average calculation; ...

"timeseries" => "time series" and "... for, e.g. ..." => "... for, e.g., ...": "A subscribing smart contract could request the full content of the channel if it required the time series for, e.g., a moving average calculation; ..."

> There is a distinct possibility that data may be tampered with whilst in transit, so off-chain methods that can attest to its integrity are critical.

Sounds a little off because the use of "it" makes it seem that the it's critical to attest to the integrity of the "distinct possibility that data may be tampered". Maybe: "There is a distinct possibility that data may be tampered with whilst in transit, so it is critical that off-chain methods are able to attest to the returned data's integrity." 

> Two approaches that are applicable here are authenticity proofs and Trusted Execution Environments (TEEs).

Maybe: "Two common approaches to data authentication are authenticity proofs and Trusted Execution Environments (TEEs)."

> TLSNotary Proofs allow a client to provide evidence to a third party that HTTPS web traffic occurred between the client and a server; while HTTPS is itself secure, it doesn’t support data signing, so TLSNotary (via PageSigner [3]) signatures are used.

I think these should be two different sentences: "TLSNotary Proofs allow a client to provide evidence to a third party that HTTPS web traffic occurred between the client and a server. These proofs rely on TLSNotary (via PageSigner [3]) signatures because while HTTPS is itself secure, it doesn’t support data signing."

> As an auditor, Oraclize use an Amazon Web Services (AWS) virtual machine instance that can be verified as unmodified since instantiation [4].

"... Orcalize uses ..."

> While offering higher assurances against data tampering than a purely trusted query/response mechanism ...

Maybe: "Although it offers higher assurances ... "

> Rather than just relaying the results of a query, computation oracles can be used to perform a relevant computation on a set of inputs, returning a calculated result that would have been infeasible to calculate on-chain.

Sounds off again: "Rather than just relaying the results of a query, computation oracles can be used to perform a relevant computation on a set of inputs and return a calculated result that may have been infeasible to calculate on-chain."

> An example might include a computationally-heavy regression calculation to estimate the yield of a bond contract.

"For example, one might use a computation oracle to perform a computationally-intensive regression calculation in order to estimate the yield of a bond contract."

> Oraclize provides a service allowing decentralized applications to request the output of a computation performed in a sandboxed AWS virtual machine.

"... a service that allows ..."

> It introduces a system of solvers and verifiers, who are each incentivized to perform computations, and verification of their correctness, respectively.

"It introduces a system of solvers and verifiers, who are incentivized to perform computations and verification of those computations, respectively."

> The game proceeds through a series of rounds, recursively checking smaller and smaller subset of the computation, until a final round. Here, the challenge is sufficiently trivial such that the judges – Ethereum miners - can make a final ruling on whether the challenge was justified, on-chain. 

"The game proceeds through a series of rounds, each recursively checking a smaller and smaller subset of the computation. The game eventually reaches a final round, where the challenge is sufficiently trivial such that the judges – Ethereum miners – can make a final ruling on whether the challenge was justified, on-chain."

> ... a reputation contract, an order-matching contract, and an aggregation contract, along with an off-chain registry of data providers.

Parallelism (sort of): "a reputation contract, an order-matching contract, an aggregation contract, and an off-chain registry of data providers."

> The reputation contract is used to keep track of data providers' performance, with scores being used to populate the off-chain registry.

"The reputation contract is used to keep track of data provider's performance. Scores in the reputation contract are used to populate the off-chain registry."

> The order-matching contract selects bids from oracles using the reputation contract, before finalizing a Service Level Agreement (SLA) - which would include query parameters and the number of oracles required - meaning the purchaser needn’t transact with the individual oracles directly.

Can be split into multiple sentences for readability: "The order-matching contract selects bids from oracles using the reputation contract. It then finalizes a Service Level Agreement (SLA), which includes query parameters and the number of oracles required. This means that the purchaser needn’t transact with the individual oracles directly."

> The aggregation contract collects responses from multiple oracles, submitted using a commit/reveal scheme, and calculates the final collective result of the query, feeding the results back into the reputation contract.

"The aggregation contract collects responses, submitted using a commit/reveal scheme, from multiple oracles, calculates the final collective result of the query, and feeds the results back into the reputation contract."

> A common point, also known as the Schelling Point, which respondents might consider as the natural and obvious target around which to coordinate, is expected to be close to the actual value.

Last comma is erroneous: "A common point, also known as the Schelling Point, which respondents might consider as the natural and obvious target around which to coordinate is expected to be close to the actual value." I think the sentence needs some general re-working.

> "They leverage a dedicated proof-of-work blockchain ..." 

"They" is a little weird. 

> "Miners attempt to download, store and propagate ..."

Plz oxford comma.

**Comment by aantonop** [comment] 2018-04-13 23:21
@kfichter Can you make a pull request with these changes, or should I turn these suggestions over to one of the editors? Thanks!

**Comment by smartcontracts** [comment] 2018-04-13 23:25
@aantonop would be more than happy to submit the PR. Will do in a few.

**Comment by SylTi** [comment] 2018-04-14 00:59
> In practical terms, an oracle might be implemented as a system of on-chain smart contracts and off-chain infrastructure used to monitor requests, retrieve and return data.

I do not agree with this statement. 
An oracle doesn't need to be automatized at all. Anybody can play the role of an oracle in resolving conflicts. You can even have more than one person playing that role in the case of a "Tribunal Oracle" like 5 peoples votes and majority win (I have seen cases where the all the token owners are expected to vote as oracles.)

I think we should have 2 sections one for manual oracle and one for automatized.

**Comment by smartcontracts** [comment] 2018-04-14 01:02
@SylTi Although I might call that a form of primitive "off-chain infrastructure", I'm inclined to agree :'-). It should probably be further explained that oracles are a much more general idea and that automated oracles are a subset of this idea.

**Comment by SylTi** [comment] 2018-04-14 01:12
Yep, after all a 2 of 3 multisig is already kind of an oracle

**Comment by timnugent** [comment] 2018-04-14 10:22
@kfichter thanks for these corrections - broadly agree with them all. The list of example use cases was intended to be whittled down and perhaps re-ordered too

**Comment by timnugent** [comment] 2018-04-14 10:24
@SylTi the emphasis in that statement was on one practical implementation, but I don't think it excludes the non-automated scheme you describe. Further down it says "A range of alternative schemes are also possible" and also mentions human-based oracles. Perhaps you can add something around there?

**Comment by SylTi** [comment] 2018-04-14 10:56
@timnugent Sure I will try to add some additional informations but I need to finish up the draft I'm working on for the upgradability patterns. 
I will do a PR on this afterward

**Closed as completed** 2018-11-02 20:24 UTC
Labels: review needed
